options:
  input_period:
    type: int
    default: 5
    description: how often a docker stat is sent to the output
  docker_socket:
    type: string
    default: unix:///var/run/docker.sock
    description: Socket to connect to the docker engine
  enable_tls:
    type: boolean
    default: False
    description: Enable tls when communicating with docker
  docker_ca_path:
    type: string
    default: /etc/docker/ca.pem
    description: Path on disk to the TLS certificate authority 
  docker_cert_path:
    type: string
    default: /etc/docker/cert.pem
    description: Path on disk to the TLS certificate

  docker_key_path:
    type: string
    default: /etc/docker/key.pem
    description: Path on disk to the TLS key
  fallback_url:
    type: string
    default: https://github.com/Ingensi/dockerbeat/releases/download/v1.0.0-rc1/dockerbeat-1.0.0-rc1-x86_64
    description: URL to download dockerbeat binary release
  fallback_sum:
    type: string
    default: c68767814e7f3bf256da52b28281a44bf392fecd
    description: SHA1 sum of fallback_url payload
